
#src/nubra_python_sdk/trading/trade_enum.py
from enum import Enum
import msgspec # type: ignore

class TradingAPIVersion(str, Enum):
    V1 = "V1"
    V2 = "V2"

class OrderSideEnum(str, Enum):
    ORDER_SIDE_BUY= "ORDER_SIDE_BUY"
    ORDER_SIDE_SELL= "ORDER_SIDE_SELL"


class OrderStatusEnum(str, Enum):
  ORDER_STATUS_PENDING= "ORDER_STATUS_PENDING"
  ORDER_STATUS_SENT = "ORDER_STATUS_SENT"
  ORDER_STATUS_OPEN = "ORDER_STATUS_OPEN"
  ORDER_STATUS_REJECTED = "ORDER_STATUS_REJECTED"
  ORDER_STATUS_CANCELLED = "ORDER_STATUS_CANCELLED"
  ORDER_STATUS_FILLED = "ORDER_STATUS_FILLED"
  ORDER_STATUS_EXPIRED = "ORDER_STATUS_EXPIRED"
  ORDER_STATUS_TRIGGERED = "ORDER_STATUS_TRIGGERED"
  ORDER_STATUS_PARTIAL_FILLED = "ORDER_STATUS_PARTIAL_FILLED"



class ExecutionTypeEnum(str, Enum):
    """Enumerates possible execution types for an order."""
    STRATEGY_TYPE_LIMIT= "STRATEGY_TYPE_LIMIT"
    STRATEGY_TYPE_MARKET= "STRATEGY_TYPE_MARKET"
    STRATEGY_TYPE_IOC= "STRATEGY_TYPE_IOC"
    STRATEGY_TYPE_ICEBERG= "STRATEGY_TYPE_ICEBERG"
    STRATEGY_TYPE_STOPLOSS= "STRATEGY_TYPE_STOPLOSS"
    STRATEGY_TYPE_VWAP= "STRATEGY_TYPE_VWAP"
    STRATEGY_TYPE_TWAP= "STRATEGY_TYPE_TWAP"
    STRATEGY_TYPE_CLOSE= "STRATEGY_TYPE_CLOSE"

class DeliveryTypeEnum(str, Enum):
    """Enumerates delivery types for orders."""
    ORDER_DELIVERY_TYPE_IDAY= "ORDER_DELIVERY_TYPE_IDAY"
    ORDER_DELIVERY_TYPE_CNC= "ORDER_DELIVERY_TYPE_CNC"

class OrderTypeEnum(str, Enum):
    """Enumerates types of orders."""
    ORDER_TYPE_LIMIT= "ORDER_TYPE_LIMIT"
    ORDER_TYPE_MARKET= "ORDER_TYPE_MARKET"

class RequestTypeEnum(str , Enum):
    ORDER_REQUEST_NEW= "ORDER_REQUEST_NEW"
    ORDER_REQUEST_MOD= "ORDER_REQUEST_MOD"
    ORDER_REQUEST_CANCEL = "ORDER_REQUEST_CANCEL"


class OrderTypeEnumV2(str, Enum):
    ORDER_TYPE_REGULAR = "ORDER_TYPE_REGULAR"
    ORDER_TYPE_VWAP = "ORDER_TYPE_VWAP"
    ORDER_TYPE_TWAP = "ORDER_TYPE_TWAP"
    ORDER_TYPE_CLOSE = "ORDER_TYPE_CLOSE"
    ORDER_TYPE_STOPLOSS = "ORDER_TYPE_STOPLOSS"
    ORDER_TYPE_ICEBERG = "ORDER_TYPE_ICEBERG"
    ORDER_TYPE_SCALING = "ORDER_TYPE_SCALING"
    ORDER_TYPE_TRAILING_SL= "ORDER_TYPE_TRAILING_SL"


class ValidityTypeEnumV2(str, Enum):
    DAY = "DAY"
    IOC = "IOC"

class PriceTypeEnumV2(str, Enum):
    LIMIT = "LIMIT"
    MARKET = "MARKET"


class BenchMarkTypeV2(str, Enum):
    MANUAL = "MANUAL"
    VWAP = "VWAP"
    ARRIVAL = "ARRIVAL"


class ExchangeEnum(str, Enum):
    NSE = "NSE"
    BSE = "BSE"




class BasketStatusEnum(str, Enum):
    BASKET_STATUS_OPEN  = "BASKET_STATUS_OPEN"
    BASKET_STATUS_FILLED = "BASKET_STATUS_FILLED"
    BASKET_STATUS_REJECTED = "BASKET_STATUS_REJECTED"
    BASKET_STATUS_CANCELLED = "BASKET_STATUS_CANCELLED"
    BASKET_STATUS_PENDING = "BASKET_STATUS_PENDING"
    BASKET_STATUS_CLOSED = "BASKET_STATUS_CLOSED"

class BasketStrategyEnum(str, Enum) :
  BASKET_STRATEGY_BULL_CALL_SPREAD = "BASKET_STRATEGY_BULL_CALL_SPREAD"
  BASKET_STRATEGY_BEAR_CALL_SPREAD = "BASKET_STRATEGY_BEAR_CALL_SPREAD"
  BASKET_STRATEGY_LONG_STRADDLE = "BASKET_STRATEGY_LONG_STRADDLE"
  BASKET_STRATEGY_SHORT_STRADDLE = "BASKET_STRATEGY_SHORT_STRADDLE"
  BASKET_STRATEGY_BULL_BUTTERFLY = "BASKET_STRATEGY_BULL_BUTTERFLY"
  BASKET_STRATEGY_BULL_CONDOR = "BASKET_STRATEGY_BULL_CONDOR"
  BASKET_STRATEGY_BEAR_CONDOR = "BASKET_STRATEGY_BEAR_CONDOR"
  BASKET_STRATEGY_BULL_PUT_SPREAD = "BASKET_STRATEGY_BULL_PUT_SPREAD"
  BASKET_STRATEGY_BEAR_PUT_SPREAD = "BASKET_STRATEGY_BEAR_PUT_SPREAD"
  BASKET_STRATEGY_IRON_CONDOR = "BASKET_STRATEGY_IRON_CONDOR"
  BASKET_STRATEGY_BEAR_BUTTERFLY = "BASKET_STRATEGY_BEAR_BUTTERFLY"
  BASKET_STRATEGY_IRON_BUTTERFLY = "BASKET_STRATEGY_IRON_BUTTERFLY"
  BASKET_STRATEGY_CUSTOM = "BASKET_STRATEGY_CUSTOM"
  BASKET_STRATEGY_TWAP = "BASKET_STRATEGY_TWAP"
  BASKET_STRATEGY_SCALING = "BASKET_STRATEGY_SCALING"
  BASKET_STRATEGY_VWAP = "BASKET_STRATEGY_VWAP"


class ExecutionTypeEnum(str, Enum):
  EXCUTION_TYPE_INVALID = "EXCUTION_TYPE_INVALID"
  EXECUTION_TYPE_FLEXI = "EXECUTION_TYPE_FLEXI"
  EXECUTION_TYPE_STOPLOSS = "EXECUTION_TYPE_STOPLOSS"
  EXECUTION_TYPE_VWAP = "EXECUTION_TYPE_VWAP"
  EXECUTION_TYPE_TWAP = "EXECUTION_TYPE_TWAP"
  EXCUTION_TYPE_CLOSE = "EXCUTION_TYPE_CLOSE"
  EXECUTION_TYPE_SCALING = "EXECUTION_TYPE_SCALING"
  EXECUTION_TYPE_REGULAR = "EXECUTION_TYPE_REGULAR"
  EXECUTION_TYPE_ICEBERG = "EXECUTION_TYPE_ICEBERG"
  EXECUTION_TYPE_TRAILING_SL = "EXECUTION_TYPE_TRAILING_SL"

class ExecutionStatusEnum(str, Enum):
  EXECUTION_STATUS_INVALID = "EXECUTION_STATUS_INVALID"
  EXECUTION_STATUS_PENDING = "EXECUTION_STATUS_PENDING"
  EXECUTION_STATUS_SENT = "EXECUTION_STATUS_SENT"
  EXECUTION_STATUS_OPEN = "EXECUTION_STATUS_OPEN"
  EXECUTION_SATUS_REJECTED = "EXECUTION_SATUS_REJECTED"
  EXECUTION_STATUS_CANCELLED = "EXECUTION_STATUS_CANCELLED"
  EXECUTION_STATUS_FILLED = "EXECUTION_STATUS_FILLED"
  EXECUTION_STATUS_TRIGGERED = "EXECUTION_STATUS_TRIGGERED"
  EXECUTION_STATUS_CLOSED= "EXECUTION_STATUS_CLOSED"
  EXECUTION_STATUS_LIVE = "EXECUTION_STATUS_LIVE"

class OptionTypeEnum(str, Enum):
    INVALID = "INVALID"
    CALL = "CALL"
    PUT = "PUT"

